[package]
name = "matplotlib"
version = "0.2.0"
edition = "2024"
authors = ["Christophe Troestler <christophe.troestler@umons.ac.be>"]
description = "Binding to Python Matplotlib"
homepage = "https://github.com/Chris00/rust-matplotlib"
repository = "https://github.com/Chris00/rust-matplotlib.git"
documentation = "https://docs.rs/matplotlib"
license = "MIT"
keywords = ["plot", "graph", "curve", "surface"]
categories = ["science", "visualization", "mathematics", "graphics"]
rust-version = "1.85"

[dependencies]
numpy = "0.28.0"
ndarray = "0.17.2"
curve-sampling = { version = "0.6", optional = true }
num-complex = { version = "0.4.6", optional = true }

[dependencies.pyo3]
version = "0.28.2"
features = ["auto-initialize"]

[features]
default = ["curve-sampling"]

[dev-dependencies]
doc-comment = "0.3.4"
polars-core = { version = "0.53.0", features = ["fmt"] }
