/// Inspired from
/// https://matplotlib.org/stable/plot_types/index.html#plot-types
use matplotlib::{colors::Base, self as mpl, figure::Figure};
use ndarray::Array1;

/// Base name for all the PDF files generated by this script.
static BASE: &'static str = "target/plot_types_";

fn main() -> anyhow::Result<()> {
    // Pairwise data
    plot_xy()?;
    scatter_xy()?;
    bar()?;
    Ok(())
}


fn plot_xy() -> anyhow::Result<()> {
    let f = |x: f64| 4. + (2. * x).sin();
    let x2: Vec<_> = (0..25).map(|i| 10. / 25. * i as f64).collect();
    let y2 = x2.iter().cloned().map(f);

    mpl::style::using("_mpl-gallery")?;

    let fig = Figure::new()?;
    let [[mut ax]] = fig.subplots()?;

    let y2_above = y2.clone().map(|y| y + 2.5).collect();
    ax.xy(&x2, &y2_above).fmt("x").markeredgewidth(2.).plot();
    ax.fun(f, 0., 10.).linewidth(2.).plot();
    let y2_below = y2.map(|y| y - 2.5).collect();
    ax.xy(&x2, &y2_below).fmt("o-").linewidth(2.).plot();

    ax.set_xlim(0., 8.)   .set_xticks((1..8).map(f64::from))
        .set_ylim(0., 8.) .set_yticks((1..8).map(f64::from));

    fig.save().to_file(format!("{BASE}plot_xy.pdf"))?;
    Ok(())
}

fn scatter_xy() -> anyhow::Result<()> {
    use rand::RngExt;
    use rand_distr::{Normal, Distribution};
    mpl::style::using("_mpl-gallery")?;

    fn vec<T>(mut f: impl FnMut() -> T) -> Vec<T> {
        (0..24).map(|_| f()).collect()
    }

    let mut rng = rand::rng();
    let n = Normal::new(0., 2.)?;
    let x = vec(|| 4. + n.sample(&mut rng));
    let y = vec(|| 4. + n.sample(&mut rng));
    let sizes = vec(|| rng.random_range(15. .. 80.));
    let colors = vec(|| rng.random_range(15 .. 80));

    let fig = Figure::new()?;
    let [[mut ax]] = fig.subplots()?;

    ax.scatter(&x, &y).s(&sizes).cm(&colors).vmin(0.).vmax(100.).plot();

    ax.set_xlim(0., 8.)   .set_xticks((1..8).map(f64::from))
        .set_ylim(0., 8.) .set_yticks((1..8).map(f64::from));
    fig.save().to_file(format!("{BASE}scatter_xy.pdf"))?;
    Ok(())
}

fn bar() -> anyhow::Result<()> {
    mpl::style::using("_mpl-gallery")?;

    let x: Vec<_> = (0 .. 8).map(|x| 0.5 + x as f64).collect();
    let y = [4.8, 5.5, 3.5, 4.6, 6.5, 6.6, 2.6, 3.0];

    let fig = Figure::new()?;
    let [[mut ax]] = fig.subplots()?;

    ax.bar(&x, &y).width(1.).edgecolor(Base::W).linewidth(0.7).plot();

    ax.set_xlim(0., 8.)   .set_xticks(Array1::range(1., 8., 1.))
        .set_ylim(0., 8.) .set_yticks(Array1::range(1., 8., 1.));
    fig.save().to_file(format!("{BASE}bar.pdf"))?;
    Ok(())
}
