/// Inspired from
/// https://matplotlib.org/stable/plot_types/index.html#plot-types
use matplotlib::{self as mpl, figure::Figure};

/// Base name for all the PDF files generated by this script.
static BASE: &'static str = "target/plot_types_";

fn main() -> anyhow::Result<()> {
    // Pairwise data
    plot_xy()?;
    Ok(())
}


fn plot_xy() -> anyhow::Result<()> {
    let f = |x: f64| 4. + (2. * x).sin();
    let x2: Vec<_> = (0..25).map(|i| 10. / 25. * i as f64).collect();
    let y2 = x2.iter().cloned().map(f);

    mpl::style::using("_mpl-gallery")?;

    let fig = Figure::new()?;
    let [[mut ax]] = fig.subplots()?;

    let y2_above = y2.clone().map(|y| y + 2.5).collect();
    ax.xy(&x2, &y2_above).fmt("x").markeredgewidth(2.).plot();
    ax.fun(f, 0., 10.).linewidth(2.).plot();
    let y2_below = y2.map(|y| y - 2.5).collect();
    ax.xy(&x2, &y2_below).fmt("o-").linewidth(2.).plot();

    ax.set_xlim(0., 8.)   .set_xticks((1..8).map(f64::from))
        .set_ylim(0., 8.) .set_yticks((1..8).map(f64::from));

    fig.save().to_file(format!("{BASE}plot_xy.pdf"))?;
    Ok(())
}
